version: "2"

services:
  evalg:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/evalg:z
      - ./instance:/usr/local/var/evalg-instance:z
    working_dir: /usr/src/evalg
    depends_on:
      - db
    command: flask run --host 0.0.0.0 --port 5000 --reload
    environment:
      PYTHONDONTWRITEBYTECODE: "yes"
      FLASK_APP: evalg
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - ./db/main:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
