# Dockerfile for the old docker-hotel

FROM harbor.uio.no/library/docker.io-python:3.9-alpine
LABEL no.uio.contact=bnt-int@usit.uio.no

# Add docker entrypoint
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -s /usr/local/bin/docker-entrypoint.sh /

COPY evalg/migrations /usr/src/evalg/evalg/migrations

# Proxy for updates during build
ENV http_proxy="http://software-proxy.uio.no:3128"
ENV https_proxy="http://software-proxy.uio.no:3128"

# Install build-deps, then install/build deps
RUN set -ex \
    && apk update \
    && apk add --no-cache --virtual .evalg-build-deps \
            gcc \
            make \
            libc-dev \
            musl-dev \
            linux-headers \
            libffi-dev \
    && apk add --no-cache --virtual .evalg-deps \
            bash \
            git \
            libc-dev \
            logrotate \
            postgresql-dev \
            postgresql-libs \
            rsyslog

ENV PIP_DEFAULT_TIMEOUT=100 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    EVALG_CONFIG="/usr/local/var/evalg-instance/evalg_config.py" \
    FLASK_APP="evalg.wsgi"

RUN pip install --upgrade pip
RUN pip3 install setuptools_scm poetry

RUN mkdir /evalg
WORKDIR /evalg
COPY . /evalg

# Build and install evalg
RUN poetry build -f wheel
RUN pip3 install dist/evalg-*.whl

# Reset proxy -- we don't want the build image to have these
ENV http_proxy=""
ENV https_proxy=""

# Add rsyslog and logrotate config
ADD instance/evalg_rsyslog.conf /etc/rsyslog.d/evalg.conf
ADD instance/evalg_logrotate.conf /etc/logrotate.d/evalg

RUN mkdir /var/log/evalg \
    && chmod 644 /etc/logrotate.d/evalg \
    && rm /etc/logrotate.d/acpid \
    && rm /etc/logrotate.d/rsyslog

# Disable kernel logs
RUN sed -i 's/module(load="imklog")/#module(load="imklog")/g' /etc/rsyslog.conf

# Delete build deps
RUN apk del .evalg-build-deps

ENTRYPOINT ["/docker-entrypoint.sh"]
