"""Commands for handleing backup keys"""
import logging
import sys

import click
import flask
import flask.cli

import evalg


logger = logging.getLogger(__name__)


@click.command('import-master-key',
               short_help='Import a single master key.')
@flask.cli.with_appcontext
def import_master_key():
    """Prompts and imports a single master-key into the database"""
    print('Enter master key: ', end='', flush=True)
    master_key = sys.stdin.readline().strip()
    new_master_key = evalg.models.privkeys_backup.MasterKey(
        public_key=master_key,
        description='Master key generated by Flask.import-master-key')
    evalg.db.session.add(new_master_key)
    evalg.db.session.commit()


commands = tuple((
    import_master_key,
))


def init_app(app):
    """ Add commands to flask application cli. """
    for command in commands:
        app.cli.add_command(command)
