"""Add file name column

Revision ID: 08f328fa09d8
Revises: 61d39998510e
Create Date: 2019-10-15 12:35:01.987710

"""
from alembic import op
import sqlalchemy as sa
import evalg.database.types


# revision identifiers, used by Alembic.
revision = '08f328fa09d8'
down_revision = '61d39998510e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('census_file_import', sa.Column('file_name', sa.UnicodeText(), nullable=True))
    op.add_column('census_file_import_version', sa.Column('file_name', sa.UnicodeText(), autoincrement=False, nullable=True))
    op.add_column('census_file_import_version', sa.Column('file_name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('census_file_import_version', 'file_name_mod')
    op.drop_column('census_file_import_version', 'file_name')
    op.drop_column('census_file_import', 'file_name')
    # ### end Alembic commands ###
