"""remove-tag-from-voter

Revision ID: 36adda7097c4
Revises: e0c99670d3b4
Create Date: 2019-09-12 11:16:17.789949

"""
from alembic import op
import sqlalchemy as sa
import evalg.database.types


# revision identifiers, used by Alembic.
revision = '36adda7097c4'
down_revision = 'e0c99670d3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pollbook_voters', 'tag')
    op.drop_column('pollbook_voters_version', 'tag_mod')
    op.drop_column('pollbook_voters_version', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pollbook_voters_version', sa.Column('tag', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pollbook_voters_version', sa.Column('tag_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('pollbook_voters', sa.Column('tag', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
