"""Add census file import table

Revision ID: 61d39998510e
Revises: 36adda7097c4
Create Date: 2019-10-14 14:53:01.302491

"""
from alembic import op
import sqlalchemy as sa
import evalg.database.types


# revision identifiers, used by Alembic.
revision = '61d39998510e'
down_revision = '36adda7097c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('census_file_import_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('pollbook_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('census_file', sa.LargeBinary(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('import_results', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('initiated_at', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('finished_at', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('pollbook_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('census_file_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mime_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('import_results_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('initiated_at_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('finished_at_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_census_file_import_version_end_transaction_id'), 'census_file_import_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_census_file_import_version_operation_type'), 'census_file_import_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_census_file_import_version_transaction_id'), 'census_file_import_version', ['transaction_id'], unique=False)
    op.create_table('census_file_import',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('pollbook_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('census_file', sa.LargeBinary(), nullable=True),
    sa.Column('mime_type', sa.UnicodeText(), nullable=True),
    sa.Column('import_results', sa.UnicodeText(), nullable=True),
    sa.Column('initiated_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('finished_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pollbook_id'], ['pollbook_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('census_file_import')
    op.drop_index(op.f('ix_census_file_import_version_transaction_id'), table_name='census_file_import_version')
    op.drop_index(op.f('ix_census_file_import_version_operation_type'), table_name='census_file_import_version')
    op.drop_index(op.f('ix_census_file_import_version_end_transaction_id'), table_name='census_file_import_version')
    op.drop_table('census_file_import_version')
    # ### end Alembic commands ###
