"""Remove type from Election. Add template_name to ElectionGroup

Revision ID: 9f52391919e5
Revises: 
Create Date: 2019-08-23 08:03:43.392770

"""
from alembic import op
import sqlalchemy as sa
import evalg.database.types


# revision identifiers, used by Alembic.
revision = '9f52391919e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('election', 'type')
    op.add_column('election_group', sa.Column('template_name', sa.UnicodeText(), nullable=True))
    op.add_column('election_group_version', sa.Column('template_name', sa.UnicodeText(), autoincrement=False, nullable=True))
    op.add_column('election_group_version', sa.Column('template_name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('election_version', 'type_mod')
    op.drop_column('election_version', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election_version', sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('election_version', sa.Column('type_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('election_group_version', 'template_name_mod')
    op.drop_column('election_group_version', 'template_name')
    op.drop_column('election_group', 'template_name')
    op.add_column('election', sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
