"""Initial schema

Revision ID: cc2a0e03e20a
Revises: 
Create Date: 2019-09-13 08:18:52.248119

"""
from alembic import op
import sqlalchemy as sa
import evalg.database.types


# revision identifiers, used by Alembic.
revision = 'cc2a0e03e20a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ballots',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('envelope_type', sa.UnicodeText(), nullable=False),
    sa.Column('ballot_type', sa.UnicodeText(), nullable=False),
    sa.Column('ballot_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ballots_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('envelope_type', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('ballot_type', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('ballot_data', sa.LargeBinary(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('envelope_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ballot_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ballot_data_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_ballots_version_end_transaction_id'), 'ballots_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_ballots_version_operation_type'), 'ballots_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_ballots_version_transaction_id'), 'ballots_version', ['transaction_id'], unique=False)
    op.create_table('candidate_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('list_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('name', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('meta', evalg.database.types.NestedMutableJson(), autoincrement=False, nullable=True),
    sa.Column('information_url', evalg.database.types.UrlType(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('pre_cumulated', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('user_cumulated', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('list_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('meta_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('information_url_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('priority_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pre_cumulated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_cumulated_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_candidate_version_end_transaction_id'), 'candidate_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_candidate_version_operation_type'), 'candidate_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_candidate_version_transaction_id'), 'candidate_version', ['transaction_id'], unique=False)
    op.create_table('election_group_count_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('group_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('initiated_at', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('finished_at', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('audit', evalg.database.types.MutableJson(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('group_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('initiated_at_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('finished_at_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('audit_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_election_group_count_version_end_transaction_id'), 'election_group_count_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_election_group_count_version_operation_type'), 'election_group_count_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_election_group_count_version_transaction_id'), 'election_group_count_version', ['transaction_id'], unique=False)
    op.create_table('election_group_role_version',
    sa.Column('grant_id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('group_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('global_role', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('group_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('global_role_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('grant_id', 'transaction_id')
    )
    op.create_index(op.f('ix_election_group_role_version_end_transaction_id'), 'election_group_role_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_election_group_role_version_operation_type'), 'election_group_role_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_election_group_role_version_transaction_id'), 'election_group_role_version', ['transaction_id'], unique=False)
    op.create_table('election_group_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('name', evalg.database.types.MutableJson(), autoincrement=False, nullable=True),
    sa.Column('description', evalg.database.types.MutableJson(), autoincrement=False, nullable=True),
    sa.Column('meta', evalg.database.types.NestedMutableJson(), autoincrement=False, nullable=True),
    sa.Column('ou_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('public_key', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('announced_at', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('published_at', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('template_name', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('type', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('meta_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ou_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('public_key_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('announced_at_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published_at_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cancelled_at_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('template_name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_election_group_version_end_transaction_id'), 'election_group_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_election_group_version_operation_type'), 'election_group_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_election_group_version_transaction_id'), 'election_group_version', ['transaction_id'], unique=False)
    op.create_table('election_list_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('name', evalg.database.types.NestedMutableJson(), autoincrement=False, nullable=True),
    sa.Column('description', evalg.database.types.NestedMutableJson(), autoincrement=False, nullable=True),
    sa.Column('information_url', evalg.database.types.UrlType(), autoincrement=False, nullable=True),
    sa.Column('election_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('information_url_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('election_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_election_list_version_end_transaction_id'), 'election_list_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_election_list_version_operation_type'), 'election_list_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_election_list_version_transaction_id'), 'election_list_version', ['transaction_id'], unique=False)
    op.create_table('election_result_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('election_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('election_group_count_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('election_protocol', evalg.database.types.MutableJson(), autoincrement=False, nullable=True),
    sa.Column('ballots', evalg.database.types.NestedMutableJson(), autoincrement=False, nullable=True),
    sa.Column('result', evalg.database.types.MutableJson(), autoincrement=False, nullable=True),
    sa.Column('pollbook_stats', evalg.database.types.MutableJson(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('election_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('election_group_count_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('election_protocol_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ballots_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('result_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pollbook_stats_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_election_result_version_end_transaction_id'), 'election_result_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_election_result_version_operation_type'), 'election_result_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_election_result_version_transaction_id'), 'election_result_version', ['transaction_id'], unique=False)
    op.create_table('election_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('name', evalg.database.types.MutableJson(), autoincrement=False, nullable=True),
    sa.Column('description', evalg.database.types.MutableJson(), autoincrement=False, nullable=True),
    sa.Column('meta', evalg.database.types.NestedMutableJson(), autoincrement=False, nullable=True),
    sa.Column('sequence', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('start', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('end', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('information_url', evalg.database.types.UrlType(), autoincrement=False, nullable=True),
    sa.Column('contact', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('mandate_period_start', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('mandate_period_end', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('group_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('active', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('meta_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sequence_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('start_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('end_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('information_url_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('contact_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mandate_period_start_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mandate_period_end_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('group_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('active_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_election_version_end_transaction_id'), 'election_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_election_version_operation_type'), 'election_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_election_version_transaction_id'), 'election_version', ['transaction_id'], unique=False)
    op.create_table('group',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('dp_group_id', sa.UnicodeText(), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('last_update', evalg.database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_group_dp_group_id'), 'group', ['dp_group_id'], unique=False)
    op.create_table('group_external_id_type',
    sa.Column('code', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('group_external_id_type_version',
    sa.Column('code', sa.UnicodeText(), autoincrement=False, nullable=False),
    sa.Column('description', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('description_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'transaction_id')
    )
    op.create_index(op.f('ix_group_external_id_type_version_end_transaction_id'), 'group_external_id_type_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_group_external_id_type_version_operation_type'), 'group_external_id_type_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_group_external_id_type_version_transaction_id'), 'group_external_id_type_version', ['transaction_id'], unique=False)
    op.create_table('group_external_id_version',
    sa.Column('group_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.UnicodeText(), autoincrement=False, nullable=False),
    sa.Column('type_code', sa.UnicodeText(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('group_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('external_id', 'type_code', 'transaction_id')
    )
    op.create_index(op.f('ix_group_external_id_version_end_transaction_id'), 'group_external_id_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_group_external_id_version_operation_type'), 'group_external_id_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_group_external_id_version_transaction_id'), 'group_external_id_version', ['transaction_id'], unique=False)
    op.create_table('group_membership_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('group_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('person_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('group_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('person_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_group_membership_version_end_transaction_id'), 'group_membership_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_group_membership_version_operation_type'), 'group_membership_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_group_membership_version_transaction_id'), 'group_membership_version', ['transaction_id'], unique=False)
    op.create_table('group_principal_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('group_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('group_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_group_principal_version_end_transaction_id'), 'group_principal_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_group_principal_version_operation_type'), 'group_principal_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_group_principal_version_transaction_id'), 'group_principal_version', ['transaction_id'], unique=False)
    op.create_table('group_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('dp_group_id', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('name', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('last_update', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('dp_group_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_update_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_group_version_dp_group_id'), 'group_version', ['dp_group_id'], unique=False)
    op.create_index(op.f('ix_group_version_end_transaction_id'), 'group_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_group_version_operation_type'), 'group_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_group_version_transaction_id'), 'group_version', ['transaction_id'], unique=False)
    op.create_table('master_key',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizational_unit',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('name', evalg.database.types.JsonType(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('parent_id', evalg.database.types.UuidType(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organizational_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('organizational_unit_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('name', evalg.database.types.JsonType(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('tag', sa.String(), autoincrement=False, nullable=True),
    sa.Column('parent_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('external_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tag_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('parent_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_organizational_unit_version_end_transaction_id'), 'organizational_unit_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_organizational_unit_version_operation_type'), 'organizational_unit_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_organizational_unit_version_transaction_id'), 'organizational_unit_version', ['transaction_id'], unique=False)
    op.create_table('person',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('email', sa.UnicodeText(), nullable=True),
    sa.Column('display_name', sa.UnicodeText(), nullable=True),
    sa.Column('last_update', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('last_update_from_feide', evalg.database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_email'), 'person', ['email'], unique=False)
    op.create_table('person_external_id_version',
    sa.Column('person_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('id_type', sa.UnicodeText(), autoincrement=False, nullable=False),
    sa.Column('id_value', sa.UnicodeText(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('person_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id_type', 'id_value', 'transaction_id')
    )
    op.create_index(op.f('ix_person_external_id_version_end_transaction_id'), 'person_external_id_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_person_external_id_version_operation_type'), 'person_external_id_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_person_external_id_version_transaction_id'), 'person_external_id_version', ['transaction_id'], unique=False)
    op.create_table('person_identifier_principal_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('id_type', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('id_value', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('id_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id_value_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_person_identifier_principal_version_end_transaction_id'), 'person_identifier_principal_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_person_identifier_principal_version_operation_type'), 'person_identifier_principal_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_person_identifier_principal_version_transaction_id'), 'person_identifier_principal_version', ['transaction_id'], unique=False)
    op.create_table('person_principal_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('person_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('person_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_person_principal_version_end_transaction_id'), 'person_principal_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_person_principal_version_operation_type'), 'person_principal_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_person_principal_version_transaction_id'), 'person_principal_version', ['transaction_id'], unique=False)
    op.create_table('person_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('email', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('last_update', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('last_update_from_feide', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('email_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('display_name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_update_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_update_from_feide_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_person_version_email'), 'person_version', ['email'], unique=False)
    op.create_index(op.f('ix_person_version_end_transaction_id'), 'person_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_person_version_operation_type'), 'person_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_person_version_transaction_id'), 'person_version', ['transaction_id'], unique=False)
    op.create_table('pollbook_meta_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('name', evalg.database.types.NestedMutableJson(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('election_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('weight_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('priority_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('election_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_pollbook_meta_version_end_transaction_id'), 'pollbook_meta_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_pollbook_meta_version_operation_type'), 'pollbook_meta_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_pollbook_meta_version_transaction_id'), 'pollbook_meta_version', ['transaction_id'], unique=False)
    op.create_table('pollbook_voters_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('id_type', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('id_value', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('pollbook_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('self_added', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('reviewed', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('tag_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id_value_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pollbook_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('self_added_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reviewed_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reason_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_pollbook_voters_version_end_transaction_id'), 'pollbook_voters_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_pollbook_voters_version_operation_type'), 'pollbook_voters_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_pollbook_voters_version_transaction_id'), 'pollbook_voters_version', ['transaction_id'], unique=False)
    op.create_table('principal',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('principal_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('principal_version',
    sa.Column('id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('principal_type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('principal_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_principal_version_end_transaction_id'), 'principal_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_principal_version_operation_type'), 'principal_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_principal_version_transaction_id'), 'principal_version', ['transaction_id'], unique=False)
    op.create_table('role_version',
    sa.Column('grant_id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('target_type', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('principal_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('name_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('target_type_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('principal_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('grant_id', 'transaction_id')
    )
    op.create_index(op.f('ix_role_version_end_transaction_id'), 'role_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_role_version_operation_type'), 'role_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_role_version_transaction_id'), 'role_version', ['transaction_id'], unique=False)
    op.create_table('transaction_meta',
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.Unicode(length=255), nullable=False),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id', 'key')
    )
    op.create_table('vote_log_version',
    sa.Column('ballot_id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('voter_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('logged_at', evalg.database.types.UtcDateTime(), autoincrement=False, nullable=True),
    sa.Column('ip_addr', evalg.database.types.IpAddressType(), autoincrement=False, nullable=True),
    sa.Column('user', sa.UnicodeText(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('voter_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('logged_at_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ip_addr_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('ballot_id', 'transaction_id')
    )
    op.create_index(op.f('ix_vote_log_version_end_transaction_id'), 'vote_log_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_vote_log_version_logged_at'), 'vote_log_version', ['logged_at'], unique=False)
    op.create_index(op.f('ix_vote_log_version_operation_type'), 'vote_log_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_vote_log_version_transaction_id'), 'vote_log_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_vote_log_version_voter_id'), 'vote_log_version', ['voter_id'], unique=False)
    op.create_table('vote_version',
    sa.Column('voter_id', evalg.database.types.UuidType(), autoincrement=False, nullable=False),
    sa.Column('ballot_id', evalg.database.types.UuidType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('ballot_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('voter_id', 'transaction_id')
    )
    op.create_index(op.f('ix_vote_version_ballot_id'), 'vote_version', ['ballot_id'], unique=False)
    op.create_index(op.f('ix_vote_version_end_transaction_id'), 'vote_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_vote_version_operation_type'), 'vote_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_vote_version_transaction_id'), 'vote_version', ['transaction_id'], unique=False)
    op.create_table('election_group',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('name', evalg.database.types.MutableJson(), nullable=True),
    sa.Column('description', evalg.database.types.MutableJson(), nullable=True),
    sa.Column('meta', evalg.database.types.NestedMutableJson(), nullable=True),
    sa.Column('ou_id', evalg.database.types.UuidType(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('announced_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('published_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('cancelled_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('deleted_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('template_name', sa.UnicodeText(), nullable=True),
    sa.Column('type', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['ou_id'], ['organizational_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_external_id',
    sa.Column('group_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('external_id', sa.UnicodeText(), nullable=False),
    sa.Column('type_code', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['type_code'], ['group_external_id_type.code'], ),
    sa.PrimaryKeyConstraint('external_id', 'type_code')
    )
    op.create_table('group_membership',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('group_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('person_id', evalg.database.types.UuidType(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'person_id')
    )
    op.create_table('group_principal',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('group_id', evalg.database.types.UuidType(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['id'], ['principal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_external_id',
    sa.Column('person_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('id_type', sa.UnicodeText(), nullable=False),
    sa.Column('id_value', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id_type', 'id_value')
    )
    op.create_table('person_identifier_principal',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('id_type', sa.UnicodeText(), nullable=False),
    sa.Column('id_value', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['principal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_type', 'id_value')
    )
    op.create_table('person_principal',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('person_id', evalg.database.types.UuidType(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['principal.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('role',
    sa.Column('grant_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('principal_id', evalg.database.types.UuidType(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principal.id'], ),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_table('transaction',
    sa.Column('issued_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', evalg.database.types.IpAddressType(), nullable=True),
    sa.Column('user_id', evalg.database.types.UuidType(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.create_table('election',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('name', evalg.database.types.MutableJson(), nullable=True),
    sa.Column('description', evalg.database.types.MutableJson(), nullable=True),
    sa.Column('meta', evalg.database.types.NestedMutableJson(), nullable=True),
    sa.Column('sequence', sa.Text(), nullable=True),
    sa.Column('start', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('end', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('information_url', evalg.database.types.UrlType(), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('mandate_period_start', sa.Date(), nullable=True),
    sa.Column('mandate_period_end', sa.Date(), nullable=True),
    sa.Column('group_id', evalg.database.types.UuidType(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['election_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election_group_count',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('group_id', evalg.database.types.UuidType(), nullable=True),
    sa.Column('initiated_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('finished_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.Column('audit', evalg.database.types.MutableJson(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['election_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election_group_key_backup',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('encrypted_priv_key', sa.Text(), nullable=False),
    sa.Column('election_group_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('master_key_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', evalg.database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['election_group_id'], ['election_group.id'], ),
    sa.ForeignKeyConstraint(['master_key_id'], ['master_key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election_group_role',
    sa.Column('grant_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('group_id', evalg.database.types.UuidType(), nullable=True),
    sa.Column('global_role', sa.Boolean(), nullable=True),
    sa.CheckConstraint('global_role = true AND group_id IS NULL OR global_role IS NULL OR global_role = false', name='no_eg_when_global'),
    sa.ForeignKeyConstraint(['grant_id'], ['role.grant_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['election_group.id'], ),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_table('election_list',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('name', evalg.database.types.NestedMutableJson(), nullable=True),
    sa.Column('description', evalg.database.types.NestedMutableJson(), nullable=True),
    sa.Column('information_url', evalg.database.types.UrlType(), nullable=True),
    sa.Column('election_id', evalg.database.types.UuidType(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election_result',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('election_id', evalg.database.types.UuidType(), nullable=True),
    sa.Column('election_group_count_id', evalg.database.types.UuidType(), nullable=True),
    sa.Column('election_protocol', evalg.database.types.MutableJson(), nullable=True),
    sa.Column('ballots', evalg.database.types.NestedMutableJson(), nullable=True),
    sa.Column('result', evalg.database.types.MutableJson(), nullable=True),
    sa.Column('pollbook_stats', evalg.database.types.MutableJson(), nullable=True),
    sa.ForeignKeyConstraint(['election_group_count_id'], ['election_group_count.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pollbook_meta',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('name', evalg.database.types.NestedMutableJson(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('election_id', evalg.database.types.UuidType(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('list_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('meta', evalg.database.types.NestedMutableJson(), nullable=True),
    sa.Column('information_url', evalg.database.types.UrlType(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('pre_cumulated', sa.Boolean(), nullable=True),
    sa.Column('user_cumulated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['election_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pollbook_voters',
    sa.Column('id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('tag', sa.UnicodeText(), nullable=True),
    sa.Column('id_type', sa.UnicodeText(), nullable=False),
    sa.Column('id_value', sa.UnicodeText(), nullable=False),
    sa.Column('pollbook_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('self_added', sa.Boolean(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.UnicodeText(), nullable=True),
    sa.CheckConstraint('NOT (self_added IS true AND reviewed IS false AND verified IS true OR self_added IS false AND reviewed IS true AND verified IS true OR self_added IS false AND reviewed IS false AND verified IS false)', name='_pollbook_voter_cc_verified_status'),
    sa.ForeignKeyConstraint(['pollbook_id'], ['pollbook_meta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pollbook_id', 'id_type', 'id_value', name='_pollbook_voter_uc')
    )
    op.create_table('vote_log',
    sa.Column('ballot_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('voter_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('logged_at', evalg.database.types.UtcDateTime(), nullable=False),
    sa.Column('ip_addr', evalg.database.types.IpAddressType(), nullable=True),
    sa.Column('user', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['voter_id'], ['pollbook_voters.id'], ),
    sa.PrimaryKeyConstraint('ballot_id')
    )
    op.create_index(op.f('ix_vote_log_logged_at'), 'vote_log', ['logged_at'], unique=False)
    op.create_index(op.f('ix_vote_log_voter_id'), 'vote_log', ['voter_id'], unique=False)
    op.create_table('vote',
    sa.Column('voter_id', evalg.database.types.UuidType(), nullable=False),
    sa.Column('ballot_id', evalg.database.types.UuidType(), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['vote_log.ballot_id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['pollbook_voters.id'], ),
    sa.PrimaryKeyConstraint('voter_id')
    )
    op.create_index(op.f('ix_vote_ballot_id'), 'vote', ['ballot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_ballot_id'), table_name='vote')
    op.drop_table('vote')
    op.drop_index(op.f('ix_vote_log_voter_id'), table_name='vote_log')
    op.drop_index(op.f('ix_vote_log_logged_at'), table_name='vote_log')
    op.drop_table('vote_log')
    op.drop_table('pollbook_voters')
    op.drop_table('candidate')
    op.drop_table('pollbook_meta')
    op.drop_table('election_result')
    op.drop_table('election_list')
    op.drop_table('election_group_role')
    op.drop_table('election_group_key_backup')
    op.drop_table('election_group_count')
    op.drop_table('election')
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('role')
    op.drop_table('person_principal')
    op.drop_table('person_identifier_principal')
    op.drop_table('person_external_id')
    op.drop_table('group_principal')
    op.drop_table('group_membership')
    op.drop_table('group_external_id')
    op.drop_table('election_group')
    op.drop_index(op.f('ix_vote_version_transaction_id'), table_name='vote_version')
    op.drop_index(op.f('ix_vote_version_operation_type'), table_name='vote_version')
    op.drop_index(op.f('ix_vote_version_end_transaction_id'), table_name='vote_version')
    op.drop_index(op.f('ix_vote_version_ballot_id'), table_name='vote_version')
    op.drop_table('vote_version')
    op.drop_index(op.f('ix_vote_log_version_voter_id'), table_name='vote_log_version')
    op.drop_index(op.f('ix_vote_log_version_transaction_id'), table_name='vote_log_version')
    op.drop_index(op.f('ix_vote_log_version_operation_type'), table_name='vote_log_version')
    op.drop_index(op.f('ix_vote_log_version_logged_at'), table_name='vote_log_version')
    op.drop_index(op.f('ix_vote_log_version_end_transaction_id'), table_name='vote_log_version')
    op.drop_table('vote_log_version')
    op.drop_table('transaction_meta')
    op.drop_index(op.f('ix_role_version_transaction_id'), table_name='role_version')
    op.drop_index(op.f('ix_role_version_operation_type'), table_name='role_version')
    op.drop_index(op.f('ix_role_version_end_transaction_id'), table_name='role_version')
    op.drop_table('role_version')
    op.drop_index(op.f('ix_principal_version_transaction_id'), table_name='principal_version')
    op.drop_index(op.f('ix_principal_version_operation_type'), table_name='principal_version')
    op.drop_index(op.f('ix_principal_version_end_transaction_id'), table_name='principal_version')
    op.drop_table('principal_version')
    op.drop_table('principal')
    op.drop_index(op.f('ix_pollbook_voters_version_transaction_id'), table_name='pollbook_voters_version')
    op.drop_index(op.f('ix_pollbook_voters_version_operation_type'), table_name='pollbook_voters_version')
    op.drop_index(op.f('ix_pollbook_voters_version_end_transaction_id'), table_name='pollbook_voters_version')
    op.drop_table('pollbook_voters_version')
    op.drop_index(op.f('ix_pollbook_meta_version_transaction_id'), table_name='pollbook_meta_version')
    op.drop_index(op.f('ix_pollbook_meta_version_operation_type'), table_name='pollbook_meta_version')
    op.drop_index(op.f('ix_pollbook_meta_version_end_transaction_id'), table_name='pollbook_meta_version')
    op.drop_table('pollbook_meta_version')
    op.drop_index(op.f('ix_person_version_transaction_id'), table_name='person_version')
    op.drop_index(op.f('ix_person_version_operation_type'), table_name='person_version')
    op.drop_index(op.f('ix_person_version_end_transaction_id'), table_name='person_version')
    op.drop_index(op.f('ix_person_version_email'), table_name='person_version')
    op.drop_table('person_version')
    op.drop_index(op.f('ix_person_principal_version_transaction_id'), table_name='person_principal_version')
    op.drop_index(op.f('ix_person_principal_version_operation_type'), table_name='person_principal_version')
    op.drop_index(op.f('ix_person_principal_version_end_transaction_id'), table_name='person_principal_version')
    op.drop_table('person_principal_version')
    op.drop_index(op.f('ix_person_identifier_principal_version_transaction_id'), table_name='person_identifier_principal_version')
    op.drop_index(op.f('ix_person_identifier_principal_version_operation_type'), table_name='person_identifier_principal_version')
    op.drop_index(op.f('ix_person_identifier_principal_version_end_transaction_id'), table_name='person_identifier_principal_version')
    op.drop_table('person_identifier_principal_version')
    op.drop_index(op.f('ix_person_external_id_version_transaction_id'), table_name='person_external_id_version')
    op.drop_index(op.f('ix_person_external_id_version_operation_type'), table_name='person_external_id_version')
    op.drop_index(op.f('ix_person_external_id_version_end_transaction_id'), table_name='person_external_id_version')
    op.drop_table('person_external_id_version')
    op.drop_index(op.f('ix_person_email'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_organizational_unit_version_transaction_id'), table_name='organizational_unit_version')
    op.drop_index(op.f('ix_organizational_unit_version_operation_type'), table_name='organizational_unit_version')
    op.drop_index(op.f('ix_organizational_unit_version_end_transaction_id'), table_name='organizational_unit_version')
    op.drop_table('organizational_unit_version')
    op.drop_table('organizational_unit')
    op.drop_table('master_key')
    op.drop_index(op.f('ix_group_version_transaction_id'), table_name='group_version')
    op.drop_index(op.f('ix_group_version_operation_type'), table_name='group_version')
    op.drop_index(op.f('ix_group_version_end_transaction_id'), table_name='group_version')
    op.drop_index(op.f('ix_group_version_dp_group_id'), table_name='group_version')
    op.drop_table('group_version')
    op.drop_index(op.f('ix_group_principal_version_transaction_id'), table_name='group_principal_version')
    op.drop_index(op.f('ix_group_principal_version_operation_type'), table_name='group_principal_version')
    op.drop_index(op.f('ix_group_principal_version_end_transaction_id'), table_name='group_principal_version')
    op.drop_table('group_principal_version')
    op.drop_index(op.f('ix_group_membership_version_transaction_id'), table_name='group_membership_version')
    op.drop_index(op.f('ix_group_membership_version_operation_type'), table_name='group_membership_version')
    op.drop_index(op.f('ix_group_membership_version_end_transaction_id'), table_name='group_membership_version')
    op.drop_table('group_membership_version')
    op.drop_index(op.f('ix_group_external_id_version_transaction_id'), table_name='group_external_id_version')
    op.drop_index(op.f('ix_group_external_id_version_operation_type'), table_name='group_external_id_version')
    op.drop_index(op.f('ix_group_external_id_version_end_transaction_id'), table_name='group_external_id_version')
    op.drop_table('group_external_id_version')
    op.drop_index(op.f('ix_group_external_id_type_version_transaction_id'), table_name='group_external_id_type_version')
    op.drop_index(op.f('ix_group_external_id_type_version_operation_type'), table_name='group_external_id_type_version')
    op.drop_index(op.f('ix_group_external_id_type_version_end_transaction_id'), table_name='group_external_id_type_version')
    op.drop_table('group_external_id_type_version')
    op.drop_table('group_external_id_type')
    op.drop_index(op.f('ix_group_dp_group_id'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_election_version_transaction_id'), table_name='election_version')
    op.drop_index(op.f('ix_election_version_operation_type'), table_name='election_version')
    op.drop_index(op.f('ix_election_version_end_transaction_id'), table_name='election_version')
    op.drop_table('election_version')
    op.drop_index(op.f('ix_election_result_version_transaction_id'), table_name='election_result_version')
    op.drop_index(op.f('ix_election_result_version_operation_type'), table_name='election_result_version')
    op.drop_index(op.f('ix_election_result_version_end_transaction_id'), table_name='election_result_version')
    op.drop_table('election_result_version')
    op.drop_index(op.f('ix_election_list_version_transaction_id'), table_name='election_list_version')
    op.drop_index(op.f('ix_election_list_version_operation_type'), table_name='election_list_version')
    op.drop_index(op.f('ix_election_list_version_end_transaction_id'), table_name='election_list_version')
    op.drop_table('election_list_version')
    op.drop_index(op.f('ix_election_group_version_transaction_id'), table_name='election_group_version')
    op.drop_index(op.f('ix_election_group_version_operation_type'), table_name='election_group_version')
    op.drop_index(op.f('ix_election_group_version_end_transaction_id'), table_name='election_group_version')
    op.drop_table('election_group_version')
    op.drop_index(op.f('ix_election_group_role_version_transaction_id'), table_name='election_group_role_version')
    op.drop_index(op.f('ix_election_group_role_version_operation_type'), table_name='election_group_role_version')
    op.drop_index(op.f('ix_election_group_role_version_end_transaction_id'), table_name='election_group_role_version')
    op.drop_table('election_group_role_version')
    op.drop_index(op.f('ix_election_group_count_version_transaction_id'), table_name='election_group_count_version')
    op.drop_index(op.f('ix_election_group_count_version_operation_type'), table_name='election_group_count_version')
    op.drop_index(op.f('ix_election_group_count_version_end_transaction_id'), table_name='election_group_count_version')
    op.drop_table('election_group_count_version')
    op.drop_index(op.f('ix_candidate_version_transaction_id'), table_name='candidate_version')
    op.drop_index(op.f('ix_candidate_version_operation_type'), table_name='candidate_version')
    op.drop_index(op.f('ix_candidate_version_end_transaction_id'), table_name='candidate_version')
    op.drop_table('candidate_version')
    op.drop_index(op.f('ix_ballots_version_transaction_id'), table_name='ballots_version')
    op.drop_index(op.f('ix_ballots_version_operation_type'), table_name='ballots_version')
    op.drop_index(op.f('ix_ballots_version_end_transaction_id'), table_name='ballots_version')
    op.drop_table('ballots_version')
    op.drop_table('ballots')
    # ### end Alembic commands ###
